<!DOCTYPE html>
<html>
    <head>
        <title>Profile - <?=$name?></title>
        <?=$v->section('meta', function() { ?>
        <meta charset="UTF-8"/>
        <?php }); ?>
    </head>
    <body>
        <?php $v->component('../alerts', ['type' => 'success']) ?>
        <p>Success!</p>
        <?php $v->end(); ?>
        <?php $v->component('components::alerts', ['type' => 'error']) ?>
        <p>Sorry...</p>
        <?php $v->end(); ?>
        <?=$v->section('content')?>
        <?=$v->section('scripts')?>
        <?php // $v->insert('bad-tpl') ?>
    </body>
</html>
