<?php

namespace Templates;

use League\Plates\Template\Template;
use League\Plates\Template\TemplateClassInterface;

class Layout implements TemplateClassInterface
{

    /**
     * @param string[] $test323
     */
    public function display(Template $tpl, string|int|null $company = null, ?string $title = null, array $test323 = []): void { ?>
<html>
<head>
    <title><?=$tpl->e($title)?> | <?=$tpl->e($company)?></title>
</head>
<body>

<?=$tpl->section('content')?>

<?=$tpl->section('scripts')?>

</body>
</html>
<?php
    }
    /**
     * Autogenerated constructor
     * @param string[] $test323
    */
    public function __construct(public string|int|null $company = null, public ?string $title = null, public array $test323 = [])
    {
    }
}