<?php

namespace Templates;

use League\Plates\Template\Template;
use League\Plates\Template\TemplateClassInterface;

class Profile implements TemplateClassInterface
{

    public function display(Template $t, string $name): void { ?>
<?php $t->layout(new Layout('User Profile')) ?>
<?php // $this->layout('layout', ['title' => 'User Profile']) // this is working too and will get the example/templates/layout.php ?>

<h1>User Profile</h1>
<p>Hello, <?=$t->e($name)?>!</p>

<?php $t->insert(new Sidebar()) ?>

<?php $t->push('scripts') ?>
    <script>
        // Some JavaScript
    </script>
<?php $t->end() ?>
<?php
    }
    /**
     * Autogenerated constructor
    */
    public function __construct(public string $name)
    {
    }
}